version: '3.8'

services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      # Roles: This node is both a broker and a controller
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'

      # Listeners: 9092 for clients, 9093 for kraft controller traffic
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'

      # Single node settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
        - redis_data:/data


volumes:
  kafka_data:
  redis_data: